substitutions:
  _ARTIFACT_REGISTRY_URL: "" # Full registry URL from Terraform (e.g., us-central1-docker.pkg.dev/project/repo)

steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "${_ARTIFACT_REGISTRY_URL}/export-job:latest", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_ARTIFACT_REGISTRY_URL}/export-job:latest"]

options:
  machineType: "E2_HIGHCPU_32"
