# If you are creating a new job use beta run jobs create, but if it already exists it will return error
# If that's the case you can just use beta run jobs update
# This is defaulted to "update" here because the job already exists

steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/gemma-fine-tuning/training-job:latest",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/gemma-fine-tuning/training-job:latest",
      ]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "jobs",
        "update",
        "training-job",
        "--image=us-central1-docker.pkg.dev/$PROJECT_ID/gemma-fine-tuning/training-job:latest",
        "--region=us-central1",
        "--memory=16Gi",
        "--cpu=4",
        "--gpu=1",
        "--task-timeout=3600",
        "--set-env-vars=GCS_DATA_BUCKET_NAME=${_GCS_DATA_BUCKET_NAME},GCS_EXPORT_BUCKET_NAME=${_GCS_EXPORT_BUCKET_NAME}",
        "--set-env-vars=PROJECT_ID=$PROJECT_ID",
      ]

substitutions:
  _GCS_DATA_BUCKET_NAME: "gemma-dataset-bucket"
  _GCS_EXPORT_BUCKET_NAME: "gemma-export-bucket"

options:
  machineType: "E2_HIGHCPU_32"
