steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/gemma-fine-tuning/inference-service:latest",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/gemma-fine-tuning/inference-service:latest",
      ]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "inference-service"
      - "--image=us-central1-docker.pkg.dev/$PROJECT_ID/gemma-fine-tuning/inference-service:latest"
      - "--region=us-central1"
      - "--platform=managed"
      - "--memory=16Gi"
      - "--cpu=4"
      - "--gpu=1"
      - "--port=8080"
      - "--allow-unauthenticated"
      - "--max-instances=3"
      - "--concurrency=1"
      - "--no-gpu-zonal-redundancy"
      - "--timeout=3600"
      - "--set-env-vars=GCS_DATA_BUCKET_NAME=${PROJECT_ID}-datasets,GCS_EXPORT_BUCKET_NAME=${PROJECT_ID}-models"
      - "--set-env-vars=PROJECT_ID=$PROJECT_ID"

options:
  machineType: "E2_HIGHCPU_8"
